# suggestion_pool.py

SUGGESTION_POOL = {
    "KUNDALI": [
        "What does my Lagna (ascendant) reveal about my basic nature and health?",
        "How will the current Mahadasha affect my career and financial growth?",
        "When is the most favorable time for me to change my job or start a business?",
        "What are the strengths and weaknesses of the Sun in my birth chart?",
        "How will my relationship with my parents and siblings be according to my horoscope?",
        "What are the indicators for wealth and property in my Kundali?",
        "Are there any specific Yogas in my chart that promise fame and success?",
        "Which planets are currently causing obstacles in my professional life?",
        "When will I reach my peak financial success based on my chart?",
        "How will my education or higher studies be impacted by planetary positions?",
        "What character traits are strongest in me according to my Rasi?",
        "Will I find success in my hometown or should I move abroad?",
        "How will my health be affected by the placement of Saturn?",
        "What are the indicators of hidden talents in my birth chart?",
        "When will the current period of struggle transition into stability?",
        "What role does Jupiter play in my professional wisdom and growth?",
        "How will my social reputation evolve in the coming years?",
        "What does the 10th house say about my choice of profession?",
        "Are there any spiritual indicators in my horoscope?",
        "How will my creative abilities manifest in my career?",
        "What are the primary sources of income suggested by my planets?",
        "When is a good time for me to invest in stocks or long-term assets?",
        "How will my competitive spirit help me in my career path?",
        "What are the indicators for a stable and happy domestic life?",
        "When will I find the mental peace I have been looking for?",
        "How do the planets influence my decision-making abilities?",
        "What does my Moon sign suggest about my emotional well-being?",
        "Are there any indicators for leadership roles in my chart?",
        "How will the transit of Rahu and Ketu affect my life this year?",
        "What are the most auspicious colors and days for me?",
        "Will I be successful in competitive exams or public services?",
        "How will my legacy and inheritance be according to my 8th house?",
        "What are the indicators for long-term health and vitality?",
        "When will I see a breakthrough in my current stuck projects?",
        "What does Mercury suggest about my communication and intellect?",
        "How will my travel plans turn out this year?",
        "What are the indicators for a sharp business mind in my chart?",
        "When will I find a suitable mentor or guide for my career?",
        "How will my children's future impact my own life path?",
        "What does the Navamsha chart suggest about my long-term destiny?",
        "Are there any debt-related issues indicated in my horoscope?",
        "How will my intuitive powers develop as I grow older?",
        "What are the indicators for artistic or literary success?",
        "When will I be able to resolve my ongoing property disputes?",
        "How will my daily routine impact my long-term success?",
        "What does Mars reveal about my energy levels and drive?",
        "Are there any indicators for a career in technology or science?",
        "How will my personality change after the age of 35?",
        "What are the best industries for me to work in?",
        "When will I find the courage to take a major life risk?",
        "How will my ancestors' blessings manifest in my life?",
        "What does the 11th house suggest about my network and gains?",
        "Are there any indicators for political success in my chart?",
        "How will my dietary habits affect my planetary strengths?",
        "What are the indicators for a strong public speaking role?",
        "When will I be able to start my own charitable or spiritual work?",
        "How will my risk-taking ability change in the next decade?",
        "What does Venus suggest about my luxury and comfort levels?",
        "Are there any indicators for success in the healing or medical field?",
        "How will my spouse's luck impact my professional growth?",
        "When will I be able to build my dream home?",
        "What are the indicators for high-level management roles?",
        "How will my dedication and hard work be rewarded eventually?",
        "What does the 12th house suggest about my subconscious mind?",
        "Are there any indicators for winning legal battles in my chart?",
        "How will my adaptability help me through major transitions?",
        "What are the most powerful planetary conjunctions in my chart?",
        "When will I find stability in my fluctuating finances?",
        "How will my patience be tested by the current transit of Saturn?",
        "What are the indicators for a career in finance or banking?",
        "How will my relationship with my boss move forward?",
        "What does the 9th house suggest about my philosophical outlook?",
        "Are there any indicators for a famous second half of life?",
        "How will my focus and concentration levels evolve?",
        "What are the indicators for success in media or journalism?",
        "When will I be able to clear my old pending loans?",
        "How will my innovative ideas lead to professional success?",
        "What does the placement of Rahu suggest about my ambitions?",
        "Are there any indicators for a multi-source income stream?",
        "How will my discipline impact my planetary results?",
        "What are the indicators for high-level research and analysis?",
        "When will I find the right partner for my business venture?",
        "How will my spiritual practices strengthen my weak planets?",
        "What does the 2nd house suggest about my speech and savings?",
        "Are there any indicators for success in the luxury goods market?",
        "How will my courage and valor be recognized by society?",
        "What are the best months of the year for me to start new things?",
        "When will I feel a sense of completion in my career goals?",
        "How will my loyalty towards my work pay off in the long run?",
        "What does the 6th house suggest about my ability to handle rivals?",
        "Are there any indicators for a career in real estate or land?",
        "How will my analytical mind help me in complex situations?",
        "What are the indicators for a person recognized for their wisdom?",
        "When will I be able to balance my professional and personal life?",
        "How will my perseverance help me overcome my biggest weakness?",
        "What does the 4th house suggest about my overall happiness levels?",
        "Are there any indicators for being a successful freelancer or consultant?",
        "How will my dedication to learning new skills impact my growth?",
        "What are the indicators for travel-related professional gains?",
        "When will I feel most aligned with my true purpose in life?"
    ],
    "MATCHING": [
        "How compatible are we according to the Ashtakoot Guna system?",
        "Is there any Nadi Dosha in our compatibility, and how can it be managed?",
        "How many Gunas are matching out of 36 between us?",
        "Does our horoscope matching indicate a stable and happy marriage?",
        "What is the level of mutual understanding and mental compatibility?",
        "Will we face any significant financial issues after getting married?",
        "How will our emotional bond be based on our respective Moon signs?",
        "Is Manglik Dosha present in either of our charts, and does it affect us?",
        "How will my spouse's professional growth impact our joint life?",
        "Does our matching suggest a good relationship with our in-laws?",
        "What is our Bhakoot score, and what does it mean for our longevity?",
        "Will our combined luck lead to better prosperity after marriage?",
        "How compatible are our temperaments according to Gana matching?",
        "Does our matching indicate strong support for children and family growth?",
        "How will our communication styles align in the long term?",
        "Is there any Graha Maitri (planetary friendship) between our Lords?",
        "What are the areas of potential conflict we should be aware of?",
        "Does our matching suggest a tradition of strong family values?",
        "How will our combined charts handle major life crises together?",
        "Is our Yoni matching strong for physical and deep-level awareness?",
        "Will our marriage lead to shared gains and property accumulation?",
        "Does our matching suggest we will support each other's career goals?",
        "How well do our life purposes align according to our charts?",
        "Will we be able to settle down in a stable environment after marriage?",
        "Does our matching indicate any health concerns for either partner?",
        "How will our mutual respect evolve as we grow older together?",
        "Is there a strong spiritual connection indicated in our matching?",
        "Will our marriage be blessed with social reputation and status?",
        "Does our matching suggest a high level of trust and loyalty?",
        "How will we manage our different approaches to finance and savings?",
        "Is our matching favorable for starting a joint family business?",
        "How will our parents' influence affect our marital relationship?",
        "Does our matching indicate a balanced distribution of authority?",
        "Will we be able to resolve our differences through dialogue?",
        "Is our Vashya matching indicative of mutual attraction and respect?",
        "How will our combined domestic life be according to the 4th house?",
        "Does our matching suggest frequent travels or relocation together?",
        "Will we be able to build a strong foundation for our future children?",
        "Does our matching indicate a person who will be a pillar of support?",
        "How will our individual habits affect our collective happiness?",
        "Is our Tara matching favorable for mutual fortune and growth?",
        "Will our marriage be harmonious despite our individual differences?",
        "Does our matching suggest a deep intellectual connection?",
        "How will we handle our respective career stresses as a couple?",
        "Is our Varna matching suitable for our social and professional roles?",
        "Will our combined planetary strengths protect us from bad periods?",
        "Does our matching suggest a life of shared joys and celebrations?",
        "How will our relationship with our extended families be?",
        "Is our matching indicative of a long and healthy life together?",
        "Will we be able to adapt to each other's changing needs over time?",
        "Does our matching suggest we will be good companions in old age?",
        "How will our religious or spiritual beliefs align in marriage?",
        "Is there any specific Dosha that we need to perform remedies for?",
        "Will our marriage bring peace and prosperity to both families?",
        "Does our matching indicate a high degree of patience for each other?",
        "How will our shared hobbies or interests strengthen our bond?",
        "Is our matching favorable for a life of luxury and comfort?",
        "Will we be able to maintain our individuality while being together?",
        "Does our matching suggest a strong sense of duty towards each other?",
        "How will our conflict resolution style evolve with time?",
        "Is our matching indicative of a relationship based on true love?",
        "Will we be able to support each other's health and wellness?",
        "Does our matching suggest we will build a large social network?",
        "How will our distinct cultures or backgrounds blend in marriage?",
        "Is our matching favorable for long-term emotional stability?",
        "Will we be able to overcome the obstacles of external influences?",
        "Does our matching suggest a marriage built on mutual growth?",
        "How will our combined energy levels impact our daily life?",
        "Is our matching indicative of a partner who is very wise?",
        "Will our marriage be recognized for its harmony in our community?",
        "Does our matching suggest a relationship that gets better with age?",
        "How will our mutual curiosity keep the relationship alive?",
        "Is our matching favorable for raising talented and wise children?",
        "Will we be able to find a home that is lucky for both of us?",
        "Does our matching suggest a partner who is very hardworking?",
        "How will our travel preferences align for vacations and pilgrimages?",
        "Is our matching indicative of a very compassionate partnership?",
        "Will our combined charts bring stability to our fluctuating jobs?",
        "Does our matching suggest we will be each other's best friends?",
        "How will our shared vision for the future guide our daily choices?",
        "Is our matching favorable for a life free from major controversies?",
        "Will we be able to maintain a high level of intimacy over the years?",
        "Does our matching suggest a partner who is very supportive of family?",
        "How will our differing opinions contribute to our mutual wisdom?",
        "Is our matching indicative of a relationship that survives all odds?",
        "Will our marriage be a source of strength for our social standing?",
        "Does our matching suggest we will always have a roof over our heads?",
        "How will our mutual respect for's career impact our home life?",
        "Is our matching favorable for a life filled with laughter and joy?",
        "Will we be able to manage our in-laws' expectations effectively?",
        "Does our matching suggest a partner who is very dedicated to the home?",
        "How will our combined luck help us in purchasing jewelry or assets?",
        "Is our matching indicative of a relationship that inspires others?",
        "Will we be able to support each other's spiritual journeys?",
        "Does our matching suggest a life focused on shared goals and values?",
        "How will our mutual honesty build an unbreakable bond?",
        "Is our matching favorable for a life of continuous learning together?",
        "Will we be able to find the right balance between work and home?",
        "Does our matching suggest a partner who is very protective of us?",
        "How will our shared gratitude for life enhance our marriage?",
        "Is our matching indicative of a destiny that was meant to be?"
    ],
    "REMEDIES": [
        "Which gemstone is most suitable for my current career challenges?",
        "What are the best Lal Kitab remedies for improving financial stability?",
        "Which mantra should I chant daily to reduce my mental stress?",
        "What specific donations (Daan) should I make to pacify Shani Dev?",
        "How can I reduce the malefic effects of Rahu and Ketu in my life?",
        "Which Rudraksha bead will help boost my focus and concentration?",
        "Are there any Vastu remedies to improve the energy of my workplace?",
        "What are the remedies for Manglik Dosha to ensure a happy marriage?",
        "How can I strengthen my weak Jupiter to gain wisdom and wealth?",
        "Which planetary remedies will help in clearing my pending debts?",
        "What is the most auspicious time for me to start wearing a new stone?",
        "How to perform a simple Rahu Shanti pooja at home effectively?",
        "What are the remedies for a weak Moon to balance my emotions?",
        "Which food items should I avoid according to my current planets?",
        "How can I improve my relationship with my boss using remedies?",
        "What specific colors should I wear on different days for positive energy?",
        "Are there any remedies for Pitra Dosha indicated in my horoscope?",
        "How can I boost my child's concentration through astrological ways?",
        "What remedies will help in resolving my ongoing property disputes?",
        "Which mantra is best for overcoming fear and gaining confidence?",
        "How can I strengthen my Venus to improve my luxury and comforts?",
        "What are the remedies for Kaal Sarp Dosha to remove life obstacles?",
        "Which gemstone will help in improving my overall health and vitality?",
        "How to use simple kitchen ingredients for planetary balancing?",
        "What are the remedies for getting success in competitive exams?",
        "How can I reduce the negative impacts of an ongoing Sade Sati?",
        "Which deity should I worship to gain strength and protection?",
        "What remedies will help in finding a suitable life partner soon?",
        "How can I protect my home from negative energy using Vastu tips?",
        "What are the remedies for improving my social reputation and status?",
        "Which Rudraksha kavach is best for overall protection from rivals?",
        "How can I strengthen my Mars to gain courage and leadership skills?",
        "What specific fasts (Vrat) are recommended for my planetary peace?",
        "How to perform a simple Sun (Surya) remedy every morning?",
        "What remedies will help in overcoming chronic health issues?",
        "Which gemstone is best for improving my business profits?",
        "How can I gain the blessings of Mercury for sharp wit and intellect?",
        "What remedies are suggested for a peaceful and happy domestic life?",
        "How to pacify the negative influence of the 8th house in my chart?",
        "Which mantra will help in attracting new opportunities in my career?",
        "What are the remedies for a stable income and savings growth?",
        "How to use copper or silver vessels for planetary strengthening?",
        "What remedies will help in fulfilling my dream of owning a house?",
        "Which gemstone should I avoid wearing according to my chart?",
        "How can I reduce the severity of planetary transits this year?",
        "What are the remedies for improving my relationship with my spouse?",
        "Which Rudraksha is best for students and academics?",
        "How to perform a basic Navgraha Shanti at home every month?",
        "What remedies will help in overcoming legal troubles and lawsuits?",
        "Which mantra should I listen to for attracting positive vibrations?",
        "How can I strengthen my 10th house Lord for professional fame?",
        "What are the remedies for a weak Mercury to improve communication?",
        "How to use essential oils or aromas for balancing my aura?",
        "What remedies will help in resolving family conflicts and tensions?",
        "Which gemstone will help in maintaining emotional balance?",
        "How can I improve my creativity and artistic skills through remedies?",
        "What specific donations are good for birthdays to ensure a great year?",
        "How to use salt or water remedies for removing 'Nazar' (evil eye)?",
        "What are the remedies for a weak Sun to improve my relationship with my father?",
        "Which Rudraksha is most effective for heart health and peace?",
        "How can I boost my luck before going for an important interview?",
        "What remedies will help in finding a job in a desired country?",
        "How to perform a simple Moon (Chandra) remedy on full moon nights?",
        "What are the remedies for removing obstacles in purchasing new vehicles?",
        "Which mantra is most powerful for overall success in life?",
        "How can I strengthen my 9th house for better luck and divine support?",
        "What specific remedies will help in having a successful business partnership?",
        "How to use colors in my bedroom to improve my sleep and health?",
        "What remedies are good for overcoming laziness and lethargy?",
        "Which gemstone is best for protection during long-distance travels?",
        "How can I improve my decision-making power through planetary alignment?",
        "What are the remedies for a weak Saturn to reduce delays in work?",
        "How to use simple root remedies (Jadi) instead of expensive stones?",
        "What remedies will help in gaining social influence and power?",
        "Which mantra should I use for meditation and spiritual growth?",
        "How can I strengthen my 2nd house for better speech and savings?",
        "What specific remedies will help in overcoming phobias and anxieties?",
        "How to use yantras at home for attracting prosperity and growth?",
        "What are the remedies for improving the health of my elderly parents?",
        "Which gemstone is best for someone in the creative or media field?",
        "How can I use lighting in my home to improve planetary energies?",
        "What remedies will help in clearing my mind and removing confusion?",
        "How to perform a basic Mars (Mangal) remedy on Tuesdays?",
        "What are the remedies for a strong 11th house for continuous gains?",
        "Which Rudraksha is best for mental clarity and spiritual depth?",
        "How can I use plants or gardening for planetary balancing?",
        "What remedies will help in resolving issues related to inheritance?",
        "How to perform a simple Venus (Shukra) remedy for better love life?",
        "What specific donations are good for festive occasions?",
        "How to use sound therapy or bells for clearing home energy?",
        "What are the remedies for a weak Mercury in the business context?",
        "Which gemstone will help me remain calm during high-pressure work?",
        "How can I use charitable work to balance my malefic planets?",
        "What remedies will help in ensuring a safe and smooth journey?",
        "How to perform a basic Jupiter (Guru) remedy on Thursdays?",
        "What specific remedies will help in gaining a respected position in society?",
        "How to use mirrors in Vastu to enhance planetary positives?",
        "What are the remedies for overcoming recurrent nightmares?",
        "Which gemstone should be worn with a silver ring for better results?",
        "How to use gemstones with copper for improving health and energy?"
    ],
    "HORARY": [
        "What are the chances of me getting a new job within the next 3 weeks?",
        "Will my current investment in stocks yield a profit by next month?",
        "Should I proceed with the property deal I am considering today?",
        "When will I receive the pending payment from my previous client?",
        "Is the person asking for a partnership trustworthy for this business?",
        "Will my missing important document be found at my home soon?",
        "What is the likely outcome of my upcoming legal hearing next week?",
        "Will I be successful in the competitive exam I just appeared for?",
        "Is this a favorable time to propose to my partner today?",
        "Will my health condition improve significantly by the next full moon?",
        "Is the travel I have planned for this weekend going to be successful?",
        "Will my loan application be approved by the bank within this month?",
        "Should I buy a new vehicle in the upcoming festive season?",
        "Will my relationship with my colleague improve after the current project?",
        "Is it a good time to start a new academic course this semester?",
        "Will my stuck insurance claim be settled within the next 4 months?",
        "Should I accept the job offer I received yesterday?",
        "Will my current business venture reach its target turnover this year?",
        "Is the property I am buying free from any hidden legal issues?",
        "Will I be able to resolve my family dispute by the end of this year?",
        "When will I find a suitable tenant for my vacant apartment?",
        "Will my application for a transfer be accepted by the management?",
        "Is it a good time to launch my new mobile app next week?",
        "Will my current health treatment show positive results soon?",
        "Should I change my present residence to a new location this year?",
        "Will I be invited to the major international conference this winter?",
        "Is the person interested in me genuinely looking for a serious relationship?",
        "Will my passport or visa issues be resolved before my travel date?",
        "Should I invest in gold right now for better long-term gains?",
        "Will my child be able to get admission into their target college?",
        "Is my ongoing project going to face any major delays next month?",
        "Will my reputation in my current organization improve this year?",
        "Should I purchase the new machinery for my factory this month?",
        "Will my current disagreement with a friend be settled soon?",
        "Is the new business strategy I am implementing going to work?",
        "Will I be able to complete my higher education without any breaks?",
        "Should I sell my old property at the price I am being offered now?",
        "Will my current loan be cleared off within the next two years?",
        "Is this a lucky week for me to attend important meetings?",
        "Will my creative work be recognized by a wider audience this year?",
        "Should I hire a new team lead for my current project today?",
        "Will my lost jewelry be recovered through legal or police help?",
        "Is it a good time to start a partnership with my close friend?",
        "Will my health symptoms recur after the current medication ends?",
        "Should I apply for a scholarship for my upcoming studies today?",
        "Will my current court case be decided in my favor this year?",
        "Is the person I am meeting today going to be helpful for my career?",
        "Will my current travel plans be affected by any weather issues?",
        "Should I invest in a startup company that my friend is launching?",
        "Will my current household project be finished within the budget?",
        "Is it a favorable time to buy a new house in my current city?",
        "Will my recent misunderstanding with my spouse be cleared today?",
        "Should I start my own practice as a consultant this month?",
        "Will my current stuck funds be released by the government soon?",
        "Is the new project I am starting going to bring me fame?",
        "Will my current health anxiety be relieved after the checkup?",
        "Should I change my current car for a better model this year?",
        "Will my research proposal be accepted by the university soon?",
        "Is the new person I am hiring skilled enough for the job?",
        "Will my current trip to a spiritual place be peaceful and safe?",
        "Should I buy the new software for my business today?",
        "Will my current financial constraints be over by the next 6 months?",
        "Is it a good time for me to go on a pilgrimage this month?",
        "Will my current domestic help issues be resolved by next week?",
        "Should I enter into a major contract with this new client today?",
        "Will my current training program lead to a better salary?",
        "Is it a favorable time to perform a housewarming ceremony soon?",
        "Will my current dispute with neighbors be handled amicably?",
        "Should I take a loan for my higher education this year?",
        "Will my current artistic project be completed on time?",
        "Is the mentor I am choosing today going to guide me well?",
        "Will my current travel companion be reliable throughout the trip?",
        "Should I invest in agricultural land in my hometown now?",
        "Will my current legal notice be answered within the deadline?",
        "Is it a good time to donate a large sum to a charity today?",
        "Will my current health recovery sustain in the long run?",
        "Should I change my career path to a completely new field now?",
        "Will my current business obstacles be removed by planetary transits?",
        "Is the new hobby I am starting today going to be beneficial?",
        "Will my current application for a membership be approved?",
        "Should I buy new furniture for my living room this month?",
        "Will my current project lead to a significant promotion soon?",
        "Is the new book I am reading today going to change my outlook?",
        "Will my current travel itinerary be successful without any changes?",
        "Should I start a regular health regimen from this morning?",
        "Will my current feeling of stagnation be over by next month?",
        "Is the person I am talking to going to become a life-long friend?",
        "Will my current academic project get a high grade?",
        "Should I apply for a new debit or credit card today?",
        "Will my current property redevelopment happen smoothly?",
        "Is it a good time to plant new trees in my garden today?",
        "Will my current business expansion plans be funded soon?",
        "Should I buy a new phone or laptop for my work this month?",
        "Will my current relationship doubts be cleared after a talk today?",
        "Is the new diet I am starting going to suit my health?",
        "Will my current travel group be friendly and supportive?",
        "Should I invest in a retirement plan starting from this month?",
        "Will my current professional challenge be solved by early next week?",
        "Is the new spiritual practice I am starting today going to work?",
        "Will my current sense of purpose be clearer by the end of today?"
    ]
}

def get_random_suggestions(category: str = "KUNDALI", count: int = 3) -> list:
    """Return random unique questions from the static pool for a given category."""
    import random
    questions = SUGGESTION_POOL.get(category.upper(), SUGGESTION_POOL["KUNDALI"])
    return random.sample(questions, k=min(count, len(questions)))

def generate_initial_suggestions(is_horary: bool = False) -> list:
    """Convenience wrapper for generating initial UI suggestions."""
    category = "HORARY" if is_horary else "KUNDALI"
    return get_random_suggestions(category, count=3)
